#pragma once 

#include <iostream>
#include <string>
#include <vector>
#include <stdio.h>
#include <exception>
#include <fstream>
#include <filesystem>
#include <sstream>
#include <iomanip>
#include <cstring>
#include <codecvt>
#include <type_traits>
#include <chrono>
#include <math.h>
#include <cmath>
#include <string.h>
#include <stdlib.h>
#include <regex>
#include <source_location>
#include <functional>
#include <thread>
#include <mutex>
#include <cstdlib>
#include <ctime>
#include <locale>
#include <cstdint>
#include <future>
#include <set>
#include "kernel/definition/assert.hpp"
#include "kernel/definition/basic/language.hpp"
#include "kernel/definition/range.hpp"
#include "kernel/definition/literal.hpp"
#include "kernel/dependencies/zlib.hpp"
#include "kernel/dependencies/fmt.hpp"
#include "kernel/dependencies/json.hpp"
#include "kernel/dependencies/md5.hpp"
#include "kernel/dependencies/cpp-base64.hpp"
#include "kernel/dependencies/SHA256.hpp"
#include "kernel/dependencies/Rijndael.hpp"
#include "kernel/dependencies/SHA224CryptoServiceProvider.hpp"
#include "kernel/dependencies/libpng.hpp"
#include "kernel/dependencies/etcpak.hpp"
#include "kernel/dependencies/tinyxml2.hpp"
#include "kernel/dependencies/ETCPACK.hpp"
#include "kernel/dependencies/SHA.hpp"
#include "kernel/dependencies/lzma.hpp"
#include "kernel/dependencies/avir.hpp"
#include "kernel/dependencies/open_vcdiff.hpp"
#include "kernel/dependencies/bzip2.hpp"
#include "kernel/dependencies/zip.hpp"
#include "kernel/dependencies/dirent.hpp"
#include "kernel/dependencies/simdjson.hpp"
#include "kernel/dependencies/compile-time-regular-expressions.hpp"
#include "kernel/dependencies/canvas_ity.hpp"
#include "kernel/dependencies/tsl.hpp"