#pragma once 

#include <iostream>
#include <string>
#include <vector>
#include <stdio.h>
#include <exception>
#include <fstream>
#include <filesystem>
#include <sstream>
#include <iomanip>
#include <codecvt>
#include <type_traits>
#include "kernel/dependencies/zlib.hpp"
#include "kernel/dependencies/fmt.hpp"
#include "kernel/dependencies/json.hpp"
#include "kernel/dependencies/md5.hpp"
#include "kernel/dependencies/cpp-base64.hpp"
#include "kernel/dependencies/SHA256.hpp"
#include "kernel/dependencies/Rijndael.hpp"
#include "kernel/dependencies/SHA224CryptoServiceProvider.hpp"