#pragma once

#include "kernel/definition/assert.hpp"
#include "kernel/definition/library.hpp"
#include "kernel/definition/macro.hpp"
#include "kernel/definition/encryption/md5/common.hpp"
#include "kernel/definition/filesystem/common.hpp"
#include "kernel/definition/string/common.hpp"
#include "kernel/definition/path/common.hpp"
#include "kernel/definition/encryption/md5/common.hpp"
#include "kernel/definition/encryption/sha224/common.hpp"
#include "kernel/definition/encryption/XOR/common.hpp"
#include "kernel/definition/encryption/sha256/common.hpp"
#include "kernel/definition/encryption/base64/common.hpp"
#include "kernel/definition/encryption/Rijndael/common.hpp"