#pragma once

#include "kernel/support/texture/invoke.hpp"
#include "kernel/support/popcap/resource_group/convert.hpp"
#include "kernel/support/popcap/resource_group/common.hpp"
#include "kernel/support/popcap/res_info/common.hpp"
#include "kernel/support/popcap/res_info/convert.hpp"
#include "kernel/support/popcap/zlib/uncompress.hpp"
#include "kernel/support/popcap/zlib/compress.hpp"
#include "kernel/support/popcap/rsb/unpack.hpp"
#include "kernel/support/popcap/rsb/miscellaneous/unpack_cipher.hpp"
#include "kernel/support/popcap/rsb/pack.hpp"
#include "kernel/support/popcap/rsg/unpack.hpp"
#include "kernel/support/popcap/rsg/pack.hpp"
#include "kernel/support/popcap/rton/decode.hpp"
#include "kernel/support/popcap/rton/encode.hpp"
#include "kernel/support/popcap/newton/encode.hpp"
#include "kernel/support/popcap/newton/decode.hpp"
#include "kernel/support/popcap/compiled_text/decode.hpp"
#include "kernel/support/popcap/compiled_text/encode.hpp"
#include "kernel/support/popcap/render_effects/decode.hpp"
#include "kernel/support/popcap/render_effects/encode.hpp"
#include "kernel/support/popcap/crypt_data/encrypt.hpp"
#include "kernel/support/popcap/crypt_data/decrypt.hpp"
#include "kernel/support/popcap/cfw2/decode.hpp"
#include "kernel/support/popcap/cfw2/encode.hpp"
#include "kernel/support/popcap/pak/unpack.hpp"
#include "kernel/support/popcap/pak/pack.hpp"
#include "kernel/support/popcap/rsb_patch/decode.hpp"
#include "kernel/support/popcap/rsb_patch/encode.hpp"
#include "kernel/support/popcap/particles/encode.hpp"
#include "kernel/support/popcap/particles/decode.hpp"
#include "kernel/support/popcap/animation/decode.hpp"
#include "kernel/support/popcap/animation/encode.hpp"
#include "kernel/support/popcap/animation/convert/from_flash.hpp"
#include "kernel/support/popcap/animation/convert/to_flash.hpp"
#include "kernel/support/popcap/animation/convert/instance.hpp"
#include "kernel/support/popcap/animation/convert/resize.hpp"
#include "kernel/support/popcap/reanim/decode.hpp"
#include "kernel/support/popcap/reanim/encode.hpp"
#include "kernel/support/popcap/reanim/convert/from_flash.hpp"
#include "kernel/support/popcap/reanim/convert/to_flash.hpp"
#include "kernel/support/popcap/reanim/convert/instance.hpp"
#include "kernel/support/wwise/sound_bank/encode.hpp"
#include "kernel/support/wwise/sound_bank/decode.hpp"

namespace Sen::Kernel::Support {
	
}