name: modding
description: "Sen: Environment"
publish_to: "none"
version: 1.0.0+1
environment:
    sdk: ">=3.4.3 <4.0.0"
dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.6
    provider: ^6.1.2
    file_picker: ^8.0.6
    delightful_toast: ^1.1.0
    google_fonts: ^6.2.1
    shared_preferences: ^2.3.1
    ffi: ^2.1.2
    async: ^2.11.0
    material_symbols_icons: ^4.2777.1
    intl: any
    path: ^1.9.0
    window_manager: ^0.3.9
    desktop_drop: ^0.5.0
    image: ^4.2.0
    dynamic_color: ^1.7.0
    flutter_localizations:
        sdk: flutter
    page_transition: ^2.1.0
    flutter_local_notifications: ^17.2.3
    local_notifier: ^0.1.6
    flutter_launcher_icons: ^0.14.1
dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.0
flutter_launcher_icons:
    android: true
    ios: true
    window: true
    linux: true
    macintosh: true
    image_path: "assets/images/logo.png"
    remove_alpha_ios: true
flutter:
    uses-material-design: true
    generate: true
    assets:
        - assets/
        - assets/images/
    fonts:
        - family: GoogleSans
          fonts:
              - asset: assets/font/GoogleSans-Regular.ttf
        - family: Segoe UI
          fonts:
              - asset: assets/font/SegoeUI.ttf
